### ISSUE TITLE
Control plane API 6443

### ISSUE THREAD

**Issue by opensaas88** [lamw/vsphere-with-tanzu-basic-automated-lab-deployment#6]
For the begining congratulation for this amazing job.

I've deployed the script and everything works, 

I've launch 2 Namespaces, but the control plane API doesn't work

PS C:\tanzu\bin> .\kubectl.exe vsphere login --server=172.17.36.2 -u administrator@vsphere.local --insecure-skip-tls-verify
time="2020-12-03T20:28:11+01:00" level=error msg="Error occurred during HTTP request: Get https://172.17.36.2/wcp/loginbanner: dial tcp 172.17.36.2:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
There was an error when trying to connect to the server.\n
Please check the server URL and try again.time="2020-12-03T20:28:11+01:00" level=fatal msg="Error while connecting to host 172.17.36.2: Get https://172.17.36.2/wcp/loginbanner: dial tcp 172.17.36.2:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.."
exit status 1

PS C:\tanzu\bin> telnet 172.17.36.2 6443
Connecting To 172.17.36.2...Could not open connection to the host, on port 6443: Connect failed

https://172.17.36.130  , 131, 132  can respond  but not **172.17.37.2**

issue come from HA Proxy ?

From a VM test @172.17.36.5 I can ping  SupervisorControlPlane (130,131,132) but not haproxy & Control Plane Node IP Address

any idea ?

![1](https://user-images.githubusercontent.com/5393980/101079233-801b1080-35a7-11eb-8602-2794bf93f0b4.PNG)
![2](https://user-images.githubusercontent.com/5393980/101079236-80b3a700-35a7-11eb-968d-8c004c0e51ff.PNG)
![3](https://user-images.githubusercontent.com/5393980/101079507-ddaf5d00-35a7-11eb-9c9d-63e1741acbbf.PNG)

**Comment by odcw** [comment]
![1](https://user-images.githubusercontent.com/5393980/101079233-801b1080-35a7-11eb-8602-2794bf93f0b4.PNG)
![2](https://user-images.githubusercontent.com/5393980/101079236-80b3a700-35a7-11eb-968d-8c004c0e51ff.PNG)
